Algoritmo "idade"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
    nome : caracter
    n : inteiro
    fixado : inteiro


Inicio
      fixado <- 4000
      escreval("digite seu nome")
      leia(nome)
      escreval("digite seu valor ganho")
      leia(n)
      
      se (n >= 4000) entao
      escreval(" você ganhou !!!")
      senao
      escreval(" você não ganhou")
      fimse



Fimalgoritmo