Algoritmo "semnome"

Var

     con: inteiro
     n1: vetor [1..4] de inteiro
     n2: vetor [1..4] de inteiro
     resultado: vetor [1..4] de inteiro

Inicio

      para con de 1 ate 4 faca
      escreva ("digite o primerio numero")
      leia (n1[con])
      n2[con]<-n1[con]

      fimpara
      escreval ("",n2[1])
      escreval ("",n2[2])
      escreval ("",n2[3])
      escreval ("",n2[4])




fimalgoritmo