Algoritmo "matrizes"

Var
     m : vetor [1..15, 1..15] de inteiro
     p : vetor [1..15] de caracter
     v,r,i: inteiro

Inicio

        para i de 1 ate 15 faca

             escreval(" digite o nome do pais: ")
             leia(p[i])

        fimpara
        
        
        para v de 1 ate 15 faca
        para r de 1 ate 15 faca
        escreval(" digite o numero de casos: ")
        leia(m[v,r])
        fimpara
        fimpara
        



Fimalgoritmo